### ISSUE TITLE
Unable to Knit Lab 3

### ISSUE THREAD

**Issue by BriannaSaf98** [Watts-College/crj-507-spring-2024#12]
Working on Lab 3 and trying to knit as I go...keep getting error message 'error saving...access is denied'. This did not happen with Lab 2

**Comment by jacobtnyoung** [comment]
Hi @BriannaSaf98! Thanks for letting me know. This is a bit hard to diagnose without seeing it. So, please do the following:

1. Re-download the template and knit it without making any changes. 
2. If it *does not* knit, then there is a permission issue or some other problem that we need to diagnose on your machine. 
3. If it *does* knit, then there is a bug that was introduced when you started working through your code. If that is the case, incrementally add your code chunks to the template, knitting each time, to see where the issue is occurring.

If you still are unable to remedy the problem, send me your .Rmd file at CRJ507@asu.edu and I can take a look through and try it on my end.

Keep me posted!

**Comment by BriannaSaf98** [comment]
I was able to get it to work - thank you!

**Comment by jacobtnyoung** [comment]
Awesome! @BriannaSaf98 were you able to identify the cause of the error?

**Comment by melgg18** [comment]
Hi @BriannaSaf98 I'm having that same issue. How were you able to fix it?

**Comment by BriannaSaf98** [comment]
![Screenshot (1)](https://github.com/Watts-College/crj-507-spring-2024/assets/155908116/207f44e8-8a73-4931-ac10-85b3c8777233)


I'm having the same issue again with knitting the template for Lab 4...I've downloaded the template a few times to try and get it to work like last week, but I'm unable to knit the file without making any changes

**Comment by jacobtnyoung** [comment]
Hi @BriannaSaf98! It looks like a permissions issue on your machine. Do this:

1. Download the template again.
2. Move the template (the .Rmd file) to your desktop.
3. Open it from there and knit. 

I think the problem is that it is trying to knit from an unusual path.

If that does not work, do the following:

1. Uninstall RStudio.
2. Restart your machine.
3. Reinstall RStudio.
4. Redownload the template and try to knit.

Keep me posted.

**Comment by jacobtnyoung** [comment]
You said that you managed to get it to work last week. Did you move the file to a different folder or anything? Sometimes it helps to retrace your steps here to figure it out.

**Comment by BriannaSaf98** [comment]
Okay, I was able to get it working by moving the RMD file to my desktop - thank you!

**Comment by jacobtnyoung** [comment]
Hi @BriannaSaf98! Great. I think you are hitting a permissions issue when you move it to whatever folder it was in. Glad to hear it is working!
