### ISSUE TITLE
Lab 3 Calculate the standardized degree for each actor.

### ISSUE THREAD

**Issue by n-galanos** [Watts-College/crj-507-spring-2024#14]
I need some help with Part 1, Question 3: Calculate the standardized degree for each actor. 

When reviewing the tutorial (I attached a screenshot of what I'm referring to), I am unclear about how to connect LondonGangNet to how the tutorial shows how to calculate the standardized degree.

I have tried many different ways such as;

> deg.g <- colSums( as.matrix (LondonGangNet))
> 
> deg.g
> g <- dim( LondonGangNet )[1]
>s.deg <- deg.g / ( g-1 )
> s.deg
numeric(0)

I believe I messed up along the way with my coding since I came up with: numeric(0). 

Im also having an issue with standardized degree for Part 2 as well, getting the error "numeric(0)".

When I try to continue by coding the Mean, I receive the same "numeric(0)" error.

<img width="899" alt="Screenshot 2024-01-29 at 8 19 39 PM" src="https://github.com/Watts-College/crj-507-spring-2024/assets/157434314/9b3e3041-42c6-42d4-bac4-358b46307e4f">

**Comment by n-galanos** [comment]
No matter how many different ways I try the codes, I'm still coming up with "numeric (0)" when running standardized degree for each actor.

**Comment by jacobtnyoung** [comment]
hi @n-galanos ! Sorry you are running into this issue. The error is on the 4th line of your code. Let me show you.

Run this:

```r


# load the libraries we need
library( sna )
library( network )

# define the path location for the file
loc <- "https://github.com/jacobtnyoung/sna-textbook/raw/main/data/data-london-gang-net.rds"
LondonGangNet <- readRDS( url(loc ) )

# define the degrees
deg.g <- colSums( as.matrix( LondonGangNet ) )

# define the number of nodes
g <- dim( LondonGangNet )[1]

#print out g
g

```

You should get an indication that the object `g` is `NULL`. This is because the object `LondonGangNet` is one of class `network`, not `matrix`. So it does not have dimensionality that the `dim()` function is looking to report.

The way to overcome this is to just continue to coerce the object to a matrix, like you did in the first line of your code. So, try this:

```r
g <- dim( as.matrix( LondonGangNet ) )[1]
```

Make sense? Let me know if you are still running into issues!

**Comment by n-galanos** [comment]
Yes that worked!! Thank you so much! Is this what I will do for Part 2 Question 3 as well using CocaineDealingNet?

**Comment by jacobtnyoung** [comment]
Hi @n-galanos ! Yes, you can do it that way.

Or, you can use the `degree()` function. That is easier, I think, but it is your call.
