### ISSUE TITLE
Coords and knitting errors

### ISSUE THREAD

**Issue by jjgillis0** [Watts-College/crj-507-spring-2024#16]
Hello Professor...me again. When running this code, then trying to knit it says incomplete string and 'coords' not found. 
Thank you for your time. 

```{r}


set.seed( 605 )
rm( coords )
par( mfrow=c( 1, 2 ), 
  mar=c( 0.1, 0.5, 1, 0.1) 
  )

gplot(
  CocaineDealingNet, 
  gmode="digraph", 
  arrowhead.cex=0.5, 
  edge.col="grey40", 
  label=rownames( CocaineDealingNet ),
  label.col="red",
  label.cex=0.8,
  label.pos=1,
  vertex.cex = ideg.CocaineDealingNet+0.2,
  main="Nodes sized by Indegree",
  coord = coords
  )
```

**Comment by jjgillis0** [comment]
I removed that line and now it gives me this error:

Error: object 'ideg.CocaineDealingNet' not found

**Comment by jacobtnyoung** [comment]
Hi @jjgillis0 , that is because the object `ideg.CocaineDealingNet` is not in the workspace. Make sure you are executing the line that creates that object.

In general, the error "object.....not found" means that you are asking to use an object that has not been defined.

For example:

```r

a <- 5 + 3

# this object exists
print( a )

# this object does not exists so it returns an error
print( b)

```

Make sense?

**Comment by jjgillis0** [comment]
It does, thank you. Hopefully I can get it to work now.

**Comment by jacobtnyoung** [comment]
Awesome! @jjgillis0
