### ISSUE TITLE
Calculating Degree and wont Knit says access denied

### ISSUE THREAD

**Issue by VALERIE8703** [Watts-College/crj-507-spring-2024#19]
deg <- degree (
  LondonGangNet
  gmode ="graph"
  cmode ="degree"
)
#print it out
deg.gang

**Comment by jacobtnyoung** [comment]
Hi @VALERIE8703! Ok let's get it figured out!

The issue is that you do not have commas after each argument in the function. Try this:

```r

deg <- degree(
LondonGangNet, # needed a comma here
gmode ="graph", # and here
cmode ="degree" 
)

#print it out
deg.gang

```

Let me know if that doesn't solve the problem.

Also, please review the help page for formatting Issues. There are some pointers there for how to show R code in the comment box. Let me know if you have questions about that as well.
